unique_ids:
  assets:
    standard-page.html: LRV34S7UTGJ7UZNNPHSW5TGYTPBLHAQY
    theme.css: GYM53KSRBY3VLIPUXHD3DSZN4JTNOOZI
  forms:
    Form1: 6R2JHIUSRUBWIT4SMBBCNMVMSMIK5M4I
  modules: {}
  scripts: {}
  server_modules:
    ServerModule1: '1726681641308704061549800.1667'
